- name: yum update
  become: yes
  yum: 
    name: "*"
    state: latest

- name: install tools
  become: yes
  yum:
    name:
      - gcc-c++
      - make
      - patch
      - git
      - curl
      - zlib-devel
      - openssl-devel
      - ImageMagick-devel
      - readline-devel
      - libcurl-devel
      - libffi-devel
      - libicu-devel
      - libxml2-devel
      - libxslt-devel
      - mysql
      - mysql-devel
    state: present
    
# Gitのインストール
- name: Install git
  become: true
  yum:
    name: git
    state: present  # 入ってる状態にする
    lock_timeout: 60
    
- name: Check if the application directory exists
  stat:
    path: "{{ app_dir }}"
  register: sample_app

- name: Clone the repository
  git:
    repo: 'https://github.com/yuta-ushijima/raisetech-live8-sample-app.git'
    dest: "{{ app_dir }}"
  when: not sample_app.stat.exists